services:
  db:
    image: postgres:13-alpine
    container_name: trivia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - trivia_network

  web:
    container_name: trivia_web
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - trivia_network

volumes:
  postgres_data:
    driver: local

networks:
  trivia_network:
    driver: bridge