name: PE Pipeline

on:
  push:
    branches: [ develop, feature/dia7 ] # to test
  pull_request:
    branches: [ develop ]

jobs:
  test-and-analyze:
    name: Test, lint & analisis
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./Prueba_entrada_CC3S2/trivia_game_python

      - name: Lint with Flake8
        continue-on-error: true
        run: |
          flake8 Prueba_entrada_CC3S2/trivia_game_python/ --count --show-source --statistics

      - name: Security analysis with Bandit
        continue-on-error: true
        run: |
          bandit -r ./Prueba_entrada_CC3S2/trivia_game_python -ll

      - name: Run tests with coverage
        continue-on-error: true
        run: |
          pytest --cov=Prueba_entrada_CC3S2/trivia_game_python ./Prueba_entrada_CC3S2/trivia_game_python -v

      - name: coverage > 90%?
        continue-on-error: true
        run: |
          pytest --cov=Prueba_entrada_CC3S2/trivia_game_python --cov-report=xml --cov-report=term-missing --cov-fail-under=90 ./Prueba_entrada_CC3S2/trivia_game_python

      - name: Start FastAPI server in background
        run: |
          uvicorn Prueba_entrada_CC3S2.trivia_game_python.main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Run Locust test
        run: |
          locust -f Prueba_entrada_CC3S2/trivia_game_python/locustfile.py --headless -u 10 -r 2 -t 10s --host http://127.0.0.1:8000