name: PE Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-and-analyze:
    name: Test, lint & analisis
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./Prueba_entrada_CC3S2/trivia_game_python

      - name: Lint with Flake8
        run: |
          flake8 Prueba_entrada_CC3S2/trivia_game_python/src/ --count --show-source --statistics

      - name: Security analysis with Bandit
        run: |
          bandit -r ./Prueba_entrada_CC3S2/trivia_game_python/src -ll

      - name: unit tests with Pytest
        run: |
          pytest ./Prueba_entrada_CC3S2/trivia_game_python/src -v